// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/booking-confirmation": {
    params: {};
  };
  "/book": {
    params: {};
  };
  "/pachete": {
    params: {};
  };
  "/not-authorized": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/bookings": {
    params: {};
  };
  "/admin/availabilities": {
    params: {};
  };
  "/admin/analytics": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/auditlogs": {
    params: {};
  };
  "/admin/confirmari": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/forgot-password" | "/reset-password" | "/booking-confirmation" | "/book" | "/pachete" | "/not-authorized" | "/profile" | "/home" | "/admin" | "/admin/bookings" | "/admin/availabilities" | "/admin/analytics" | "/admin/users" | "/admin/auditlogs" | "/admin/confirmari" | "/*";
  };
  "pages/Index.tsx": {
    id: "pages/Index";
    page: "/";
  };
  "pages/AuthPage.tsx": {
    id: "pages/AuthPage";
    page: "/auth";
  };
  "pages/ForgotPasswordPage.tsx": {
    id: "pages/ForgotPasswordPage";
    page: "/forgot-password";
  };
  "pages/ResetPasswordPage.tsx": {
    id: "pages/ResetPasswordPage";
    page: "/reset-password";
  };
  "pages/BookingConfirmationPage.tsx": {
    id: "pages/BookingConfirmationPage";
    page: "/booking-confirmation";
  };
  "pages/BookingPage.tsx": {
    id: "pages/BookingPage";
    page: "/book";
  };
  "pages/PachetePage.tsx": {
    id: "pages/PachetePage";
    page: "/pachete";
  };
  "pages/NotAuthorized.tsx": {
    id: "pages/NotAuthorized";
    page: "/not-authorized";
  };
  "pages/ProfilePage.tsx": {
    id: "pages/ProfilePage";
    page: "/profile";
  };
  "routes/home-redirect.tsx": {
    id: "routes/home-redirect";
    page: "/home";
  };
  "pages/admin/DashboardLayout.tsx": {
    id: "pages/admin/DashboardLayout";
    page: "/admin" | "/admin/bookings" | "/admin/availabilities" | "/admin/analytics" | "/admin/users" | "/admin/auditlogs" | "/admin/confirmari";
  };
  "pages/admin/AdminHome.tsx": {
    id: "pages/admin/AdminHome";
    page: "/admin";
  };
  "pages/admin/Bookings.tsx": {
    id: "pages/admin/Bookings";
    page: "/admin/bookings";
  };
  "pages/admin/Availabilities.tsx": {
    id: "pages/admin/Availabilities";
    page: "/admin/availabilities";
  };
  "pages/admin/Analytics.tsx": {
    id: "pages/admin/Analytics";
    page: "/admin/analytics";
  };
  "pages/admin/Users.tsx": {
    id: "pages/admin/Users";
    page: "/admin/users";
  };
  "pages/admin/AuditLogs.tsx": {
    id: "pages/admin/AuditLogs";
    page: "/admin/auditlogs";
  };
  "pages/admin/Confirmari.tsx": {
    id: "pages/admin/Confirmari";
    page: "/admin/confirmari";
  };
  "pages/NotFound.tsx": {
    id: "pages/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/Index": typeof import("./src/pages/Index.tsx");
  "pages/AuthPage": typeof import("./src/pages/AuthPage.tsx");
  "pages/ForgotPasswordPage": typeof import("./src/pages/ForgotPasswordPage.tsx");
  "pages/ResetPasswordPage": typeof import("./src/pages/ResetPasswordPage.tsx");
  "pages/BookingConfirmationPage": typeof import("./src/pages/BookingConfirmationPage.tsx");
  "pages/BookingPage": typeof import("./src/pages/BookingPage.tsx");
  "pages/PachetePage": typeof import("./src/pages/PachetePage.tsx");
  "pages/NotAuthorized": typeof import("./src/pages/NotAuthorized.tsx");
  "pages/ProfilePage": typeof import("./src/pages/ProfilePage.tsx");
  "routes/home-redirect": typeof import("./src/routes/home-redirect.tsx");
  "pages/admin/DashboardLayout": typeof import("./src/pages/admin/DashboardLayout.tsx");
  "pages/admin/AdminHome": typeof import("./src/pages/admin/AdminHome.tsx");
  "pages/admin/Bookings": typeof import("./src/pages/admin/Bookings.tsx");
  "pages/admin/Availabilities": typeof import("./src/pages/admin/Availabilities.tsx");
  "pages/admin/Analytics": typeof import("./src/pages/admin/Analytics.tsx");
  "pages/admin/Users": typeof import("./src/pages/admin/Users.tsx");
  "pages/admin/AuditLogs": typeof import("./src/pages/admin/AuditLogs.tsx");
  "pages/admin/Confirmari": typeof import("./src/pages/admin/Confirmari.tsx");
  "pages/NotFound": typeof import("./src/pages/NotFound.tsx");
};